// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jym/mywebook/interactive/events"
	"github.com/jym/mywebook/interactive/grpc"
	"github.com/jym/mywebook/interactive/ioc"
	"github.com/jym/mywebook/interactive/repository"
	"github.com/jym/mywebook/interactive/repository/cache"
	"github.com/jym/mywebook/interactive/repository/dao"
	"github.com/jym/mywebook/interactive/service"
)

// Injectors from wire.go:

func InitGRPCServer() *App {
	db := ioc.InitDB()
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewinteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewinteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCxServe(interactiveServiceServer)
	client := ioc.InitKafka()
	logger := ioc.InitLogger()
	kafkaConsumer := events.NewKafkaConsumer(client, logger, interactiveRepository)
	v := ioc.NewConsumers(kafkaConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var interactiveSvc = wire.NewSet(service.NewinteractiveService, repository.NewinteractiveRepository, dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache)
