// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jym/mywebook/interactive/grpc"
	"github.com/jym/mywebook/interactive/ioc"
	"github.com/jym/mywebook/interactive/repository"
	"github.com/jym/mywebook/interactive/repository/cache"
	"github.com/jym/mywebook/interactive/repository/dao"
	"github.com/jym/mywebook/interactive/service"
)

// Injectors from wire.go:

func InitGRPCServer() *grpc.InteractiveServiceServer {
	db := ioc.InitDB()
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewinteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewinteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	return interactiveServiceServer
}

// wire.go:

var interactiveSvc = wire.NewSet(service.NewinteractiveService, repository.NewinteractiveRepository, dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache)
