// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jym/mywebook/internal/events/article"
	"github.com/jym/mywebook/internal/repository"
	"github.com/jym/mywebook/internal/repository/cache"
	"github.com/jym/mywebook/internal/repository/dao"
	"github.com/jym/mywebook/internal/service"
	"github.com/jym/mywebook/internal/web"
	"github.com/jym/mywebook/internal/web/jwt"
	"github.com/jym/mywebook/ioc"
	repository2 "github.com/jym/webook-interactive/repository"
	cache2 "github.com/jym/webook-interactive/repository/cache"
	dao2 "github.com/jym/webook-interactive/repository/dao"
	service2 "github.com/jym/webook-interactive/service"
)

// Injectors from wire.go:

func InitWeb() *App {
	client := ioc.InitKafka()
	logger := ioc.InitLogger()
	db := ioc.InitDB()
	interactiveDAO := dao2.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewinteractiveRepository(interactiveDAO, interactiveCache)
	kafkaConsumer := article.NewKafkaConsumer(client, logger, interactiveRepository)
	v := ioc.NewConsumers(kafkaConsumer)
	handler := jwt.NewRedisJwt(cmdable)
	v2 := ioc.InitMiddlewares(cmdable, handler)
	userDAO := dao.NewuserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewuserRepository(userDAO, userCache)
	userService := service.NewuserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewcodeRepository(codeCache)
	smsService := ioc.InitSMS(cmdable)
	codeService := service.NewcodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, cmdable, handler, logger)
	wechatService := ioc.InitWechat()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, handler)
	articleDAO := dao.NewarticleDAO(db)
	articleCache := cache.NewRedisArticle(cmdable)
	articleRepository := repository.NewarticleRepository(articleDAO, articleCache, userRepository)
	syncProducer := ioc.NewSyncProducer(client)
	producer := article.NewKafkaProducer(syncProducer)
	articleService := service.NewarticleService(articleRepository, producer)
	interactiveService := service2.NewinteractiveService(interactiveRepository)
	articleHandler := web.NewArticleHandler(articleService, interactiveService)
	engine := ioc.InitGin(v2, userHandler, oAuth2WechatHandler, articleHandler)
	rankingService := service.NewBatchRankingService(articleService, interactiveService)
	job := ioc.InitRankingJob(rankingService)
	cron := ioc.InitJobs(logger, job)
	app := &App{
		consumers: v,
		web:       engine,
		cron:      cron,
	}
	return app
}

// wire.go:

var RankingService = wire.NewSet(repository.NewrankingRepository, cache.NewRedisRankingCache, service.NewBatchRankingService)

var UserService = wire.NewSet(dao.NewuserDAO, cache.NewRedisUserCache, repository.NewuserRepository, service.NewuserService, web.NewUserHandler)

var CodeService = wire.NewSet(cache.NewRedisCodeCache, repository.NewcodeRepository, service.NewcodeService)

var ArticleService = wire.NewSet(dao.NewarticleDAO, repository.NewarticleRepository, service.NewarticleService, cache.NewRedisArticle)

var InteractiveService = wire.NewSet(dao2.NewGORMInteractiveDAO, repository2.NewinteractiveRepository, service2.NewinteractiveService, cache2.NewRedisInteractiveCache)
