// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/jym/mywebook/internal/repository"
	"github.com/jym/mywebook/internal/repository/cache"
	"github.com/jym/mywebook/internal/repository/dao"
	"github.com/jym/mywebook/internal/service"
	"github.com/jym/mywebook/internal/web"
	"github.com/jym/mywebook/internal/web/jwt"
	"github.com/jym/mywebook/ioc"
)

// Injectors from wire.go:

func InitWeb() *gin.Engine {
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJwt(cmdable)
	v := ioc.InitMiddlewares(cmdable, handler)
	db := ioc.InitDB()
	userDAO := dao.NewuserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewuserRepository(userDAO, userCache)
	userService := service.NewuserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewcodeRepository(codeCache)
	smsService := ioc.InitSMS(cmdable)
	codeService := service.NewcodeService(codeRepository, smsService)
	zapLogger := ioc.InitLogger()
	userHandler := web.NewUserHandler(userService, codeService, cmdable, handler, zapLogger)
	wechatService := ioc.InitWechat()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, handler)
	articleDAO := dao.NewarticleDAO(db)
	articleCache := cache.NewRedisArticle(cmdable)
	articleRepository := repository.NewarticleRepository(articleDAO, articleCache, userRepository)
	articleService := service.NewarticleService(articleRepository)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewinteractiveRepository(interactiveDAO, interactiveCache)
	interactiveService := service.NewinteractiveService(interactiveRepository)
	articleHandler := web.NewArticleHandler(articleService, interactiveService)
	engine := ioc.InitGin(v, userHandler, oAuth2WechatHandler, articleHandler)
	return engine
}

// wire.go:

var UserService = wire.NewSet(dao.NewuserDAO, cache.NewRedisUserCache, repository.NewuserRepository, service.NewuserService, web.NewUserHandler)

var CodeService = wire.NewSet(cache.NewRedisCodeCache, repository.NewcodeRepository, service.NewcodeService)

var ArticleService = wire.NewSet(dao.NewarticleDAO, repository.NewarticleRepository, service.NewarticleService, cache.NewRedisArticle)

var InteractiveService = wire.NewSet(dao.NewGORMInteractiveDAO, repository.NewinteractiveRepository, service.NewinteractiveService, cache.NewRedisInteractiveCache)
