mysql:
  dsn: "root:root@tcp(47.120.51.5:13316)/webook"

redis:
  addr: "47.120.51.5:6379"

kafka:
  addrs:
    - "47.120.51.5:9094"

#流量控制
#grpc:
#  client:
#    intr:
#      addr: "localhost:8090"
#      threshold: 100
etcd:
  endpoints:
    - "47.120.51.5:12379"